---
- hosts: all
  name: Prepares an SELinux workshop
  become: yes
  become_method: sudo

  tasks:

  - name: "install packages"
    ansible.builtin.yum:
      name: 
      - python3-policycoreutils
      - policycoreutils-devel
      - policycoreutils-newrole
      - selinux-policy-doc
      - setroubleshoot-server
      - setools-console
      - make
      - gcc-c++
      - libcurl-devel.x86_64
      - rpm-build
      state: present

  - name: Ensure SELinux is in enforcing mode
    ansible.posix.selinux:
      policy: targeted
      state: enforcing

  - name: Create dir with working files
    ansible.builtin.file:
      path: /root/selinuxlab
      state: directory
      mode: 0755

  - name: Ensure SELinux test app source is on the system
    ansible.builtin.copy:
      src: files/testapp.c
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure Makefile for the test app is copied to the system
    ansible.builtin.copy:
      src: files/Makefile
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure SELinux test app service file is on the system
    ansible.builtin.copy:
      src: files/testapp.service
      dest: /root/selinuxlab/testapp.service
      mode: 0644

  - name: Compile the testapp
    ansible.builtin.shell:
      cmd: "make -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

  - name: Install the testapp
    ansible.builtin.shell:
      cmd: "make install -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

...
